---
apiVersion: v1
kind: ConfigMap
metadata:
  name: akhq-config
  namespace: flink
data:
  application.yml: |
    akhq:
      connections:
        local:
          properties:
            bootstrap.servers: "my-cluster-kafka-bootstrap:9092"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: akhq
  namespace: flink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akhq
  template:
    metadata:
      labels:
        app: akhq
    spec:
      containers:
      - name: akhq
        image: tchiotludo/akhq:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /app/application.yml
          subPath: application.yml
      volumes:
      - name: config
        configMap:
          name: akhq-config
---
apiVersion: v1
kind: Service
metadata:
  name: akhq
  namespace: flink
spec:
  type: NodePort
  selector:
    app: akhq
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32096

