apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-session-filter
spec:
  image: flink:1.20-java17
  imagePullPolicy: Always
  flinkVersion: v1_20
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 0.5
  taskManager:
    resource:
      memory: "2048m"
      cpu: 0.5