---
apiVersion: flink.apache.org/v1beta1
kind: FlinkSessionJob
metadata:
  name: flink-session-job
  namespace: flink
spec:
  deploymentName: flink-session-filter

  job:
    jarURI: http://minio.minio:9000/test/flink-filter.jar
    entryClass: org.example.KafkaHighValuePurchaseFilterJob
    parallelism: 2
    upgradeMode: stateless
