---
apiVersion: flink.apache.org/v1beta1
kind: FlinkSessionJob
metadata:
  name: flink-session-job
  namespace: flink
spec:
  deploymentName: flink-session-filter

  job:
    jarURI: http://minio.minio:9000/test/flink-filter.jar
    entryClass: org.example.KafkaHighValuePurchaseFilterJob
    parallelism: 2
    upgradeMode: stateless
---
apiVersion: v1
kind: Service
metadata:
  name: flink-rest-nodeport
  namespace: flink
spec:
  type: NodePort
  selector:
    app: flink-session-filter
    component: jobmanager
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 32097

